### ISSUE TITLE
Abnormal CPU overload

### ISSUE THREAD

**Issue by KimHono** [linuxdeepin/deepin-reader#15]
Hi!
Today I noticed an abnormal CPU overload of my computer. Curiously, this is visible when 2 or more files are opened simultaneously in Deepin-Reader.
To understand, here are mean values monitored by `top`:
- 44 % CPU workload with 2 files
- 0 % CPU workload with 1 file

During a test **lauch > open-1 file > open 2 files > close** I copied these messages from the terminal:
`QApplication: invalid style override 'gtk' passed, ignoring it.
        Available styles: bb10dark, bb10bright, chameleon, cleanlooks, gtk2, cde, motif, plastique, Windows, Fusion
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 5 (BadAtom), sequence: 403, resource id: 0, major code: 20 (GetProperty), minor code: 0
2020-12-12, 21:20:07.961 [Warning] [                                                         0] window == 0 passed.
No appenders assotiated with category qt.qpa.xcb
[Warning] <> QXcbConnection: XCB error: 152 (Unknown), sequence: 62304, resource id: 0, major code: 143 (Unknown), minor code: 2`

My system is : 5.9.13-arch1-1
Package _deepin-reader_ version 5.8.0.1-2

**Comment by samson-sofun** [comment]
Thanks for your test results.
We noticed this problem because we used a dtk widget that would cause this bug.We have informed them, and in the meantime we have temporarily removed the code. Now it's ok in the dev branch,  the latest tag is 5.9.0.3.
