### ISSUE TITLE
目录显示页码不全

### ISSUE THREAD

**Issue by hadejia** [linuxdeepin/deepin-reader#16]
如图，页码在3位数及以上就显示不全了
![image](https://user-images.githubusercontent.com/34773099/109373792-fea7f580-78eb-11eb-89f8-cea639529793.png)

**Comment by hadejia** [comment]
？？？

**Comment by z966768** [comment]
试试新版本，新版本已修改

**Comment by hadejia** [comment]
> 试试新版本，新版本已修改
uos商店里好像没推送新版本
