### ISSUE TITLE
feature request: pop up of quick actions on text selection

### ISSUE THREAD

**Issue by sidmint** [linuxdeepin/deepin-reader#17]
pop up of quick actions upon text selection, like highlighting, copy, underline, etc. would be very useful. Otherwise right click on selected text and selection of option through cursor is required currently.

Thank you, this app is seeing really good progress.

**Comment by ifdu-code** [comment]
> pop up of quick actions upon text selection, like highlighting, copy, underline, etc. would be very useful. Otherwise right click on selected text and selection of option through cursor is required currently.
> 
> Thank you, this app is seeing really good progress.

This is a good idea. We will provide it to PM for evaluation. Thank you for your support!

**Comment by Sky-Asher** [comment]
Thank you for your support. I have fed back this question to the product manager.
