### ISSUE TITLE
Dependencies list correction in documentation

### ISSUE THREAD

**Issue by sidmint** [linuxdeepin/deepin-reader#18]
Following would be easier to paste into terminal at one go [removed commas and put equal spaces]:

sudo apt install debhelper pkg-config libspectre-dev libdjvulibre-dev qt5-qmake qt5-default libtiff-dev libkf5archive-dev libdtkwidget-dev qttools5-dev-tools qtbase5-private-dev libjpeg-dev libicu-dev libpng-dev zlib1g-dev

And mention debhelper (>= 11) separately.

**Comment by YutianGe** [comment]
Thank you for your feedback
