### ISSUE TITLE
REQUEST FEATURES LIKE ADD SIGNATURE,TEXT AND STAMP IN PDF VIEWER

### ISSUE THREAD

**Issue by sarojpoudel33** [linuxdeepin/deepin-reader#19]
**How to add a signature to a PDF**
Open the PDF file in Adobe Acrobat Reader.
Click on Fill & Sign in the Tools pane on the right.
Click Sign, and then select Add Signature.
A popup will open, giving you three options—Type, Draw, and Image. ...
Drag, resize and position the signature inside your PDF file.

*We Need This Option In Our PDF Viewer.

@hualet 
@deepinAdmin 
@felixonmars

**Comment by ifdu-code** [comment]
> **How to add a signature to a PDF**
> Open the PDF file in Adobe Acrobat Reader.
> Click on Fill & Sign in the Tools pane on the right.
> Click Sign, and then select Add Signature.
> A popup will open, giving you three options—Type, Draw, and Image. ...
> Drag, resize and position the signature inside your PDF file.
> 
> *We Need This Option In Our PDF Viewer.
> 
> @hualet
> @deepinAdmin
> @felixonmars

This is a good idea. We will provide it to PM for evaluation. Thank you for your support!

**Comment by Sky-Asher** [comment]
Thank you for your support. I have fed back this question to the product manager.
