### ISSUE TITLE
make error without DSplitter

### ISSUE THREAD

**Issue by WXZhao7** [linuxdeepin/deepin-reader#20]
Platform:
- OS: Ubuntu 20.04 focal
- Kernel: x86_64 Linux 5.11.0-27-generic
- DE: GNOME 3.36.5

Q: **I had install all the dependencies, and I can't find ant info about DSplitter on the internet. ???**

![image](https://user-images.githubusercontent.com/56864878/130549653-439aefb0-9abf-43ac-ac00-62df4bc89202.png)
![image](https://user-images.githubusercontent.com/56864878/130549688-0cb9d0fa-7e09-4fdf-a7e4-0241d5234ccf.png)
```shell
g++ -c -pipe -fPIE -O2 -std=gnu++11 -pthread -Wall -W -D_REENTRANT -fPIC -DPERF_ON -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -Iuiframe -I../3rdparty/deepin-pdfium/include -Iapp -Ibrowser -Isidebar -Iwidgets -Idocument -isystem /usr/include/libdtk-2.1.1/DWidget -isystem /usr/include/libdtk-2.1.1/DCore -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o Json.o app/Json.cpp
g++ -c -pipe -fPIE -O2 -std=gnu++11 -pthread -Wall -W -D_REENTRANT -fPIC -DPERF_ON -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -Iuiframe -I../3rdparty/deepin-pdfium/include -Iapp -Ibrowser -Isidebar -Iwidgets -Idocument -isystem /usr/include/libdtk-2.1.1/DWidget -isystem /usr/include/libdtk-2.1.1/DCore -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o Database.o app/Database.cpp
In file included from app/Database.cpp:30:
uiframe/DocSheet.h:26:10: fatal error: DSplitter: No such file or directory
   26 | #include <DSplitter>
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:1202: Database.o] Error 1
make[1]: Leaving directory '/home/wxz/Program/deepin-reader/src'
make: *** [Makefile:47: sub-src-make_first] Error 2
```

**Comment by ifdu-code** [comment]
> Platform:
> 
> * OS: Ubuntu 20.04 focal
> * Kernel: x86_64 Linux 5.11.0-27-generic
> * DE: GNOME 3.36.5
> 
> Q: **I had install all the dependencies, and I can't find ant info about DSplitter on the internet. ???**
> 
> ![image](https://user-images.githubusercontent.com/56864878/130549653-439aefb0-9abf-43ac-ac00-62df4bc89202.png)
> ![image](https://user-images.githubusercontent.com/56864878/130549688-0cb9d0fa-7e09-4fdf-a7e4-0241d5234ccf.png)
> 
> ```shell
> g++ -c -pipe -fPIE -O2 -std=gnu++11 -pthread -Wall -W -D_REENTRANT -fPIC -DPERF_ON -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -Iuiframe -I../3rdparty/deepin-pdfium/include -Iapp -Ibrowser -Isidebar -Iwidgets -Idocument -isystem /usr/include/libdtk-2.1.1/DWidget -isystem /usr/include/libdtk-2.1.1/DCore -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o Json.o app/Json.cpp
> g++ -c -pipe -fPIE -O2 -std=gnu++11 -pthread -Wall -W -D_REENTRANT -fPIC -DPERF_ON -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -Iuiframe -I../3rdparty/deepin-pdfium/include -Iapp -Ibrowser -Isidebar -Iwidgets -Idocument -isystem /usr/include/libdtk-2.1.1/DWidget -isystem /usr/include/libdtk-2.1.1/DCore -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o Database.o app/Database.cpp
> In file included from app/Database.cpp:30:
> uiframe/DocSheet.h:26:10: fatal error: DSplitter: No such file or directory
>    26 | #include <DSplitter>
>       |          ^~~~~~~~~~~
> compilation terminated.
> make[1]: *** [Makefile:1202: Database.o] Error 1
> make[1]: Leaving directory '/home/wxz/Program/deepin-reader/src'
> make: *** [Makefile:47: sub-src-make_first] Error 2
> ```

Please try to install the version of libdtkwidget-dev>=5.4.0

**Comment by WXZhao7** [comment]
> Please try to install the version of libdtkwidget-dev>=5.4.0

The latest libdtkwidget-dev(stable) is [5.2.2.10](https://pkgs.org/download/libdtkwidget-dev) or libdtkwidget-dev(Experimental) [5.5.17.1-1~exp1](https://packages.debian.org/experimental/libdevel/libdtkwidget-dev). I tried them but libdtkwidget-dev caused other dependency problems. Solving these dependency is troublesome(need other source...), so I go back to evince~
```shell
❯ sudo dpkg -i libdtkwidget-dev_5.5.17.1-1~exp1_amd64.deb
(Reading database ... 353656 files and directories currently installed.)
Preparing to unpack libdtkwidget-dev_5.5.17.1-1~exp1_amd64.deb ...
Unpacking libdtkwidget-dev:amd64 (5.5.17.1-1~exp1) over (2.1.1-1build3) ...
dpkg: dependency problems prevent configuration of libdtkwidget-dev:amd64:
 libdtkwidget-dev:amd64 depends on libcups2-dev; however:
  Package libcups2-dev is not installed.
 libdtkwidget-dev:amd64 depends on libdtkcore-dev (>= 5.5.17); however:
  Version of libdtkcore-dev:amd64 on system is 2.1.1-1build1.
 libdtkwidget-dev:amd64 depends on libdtkgui-dev (>= 5.5.17); however:
  Package libdtkgui-dev is not installed.
 libdtkwidget-dev:amd64 depends on libdtkwidget5 (= 5.5.17.1-1~exp1); however:
  Package libdtkwidget5 is not installed.
 libdtkwidget-dev:amd64 depends on libqt5svg5-dev; however:
  Package libqt5svg5-dev is not installed.

dpkg: error processing package libdtkwidget-dev:amd64 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libdtkwidget-dev:amd64
❯ sudo apt install libcups2-dev libdtkgui-dev libdtkwidget5 libqt5svg5-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libdtkgui-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libdtkwidget5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libdtkgui-dev' has no installation candidate
E: Package 'libdtkwidget5' has no installation candidate
```

**Comment by ifdu-code** [comment]
> > Please try to install the version of libdtkwidget-dev>=5.4.0
> 
> The latest libdtkwidget-dev(stable) is [5.2.2.10](https://pkgs.org/download/libdtkwidget-dev) or libdtkwidget-dev(Experimental) [5.5.17.1-1~exp1](https://packages.debian.org/experimental/libdevel/libdtkwidget-dev). I tried them but libdtkwidget-dev caused other dependency problems. Solving these dependency is troublesome(need other source...), so I go back to evince~
> 
> ```shell
> ❯ sudo dpkg -i libdtkwidget-dev_5.5.17.1-1~exp1_amd64.deb
> (Reading database ... 353656 files and directories currently installed.)
> Preparing to unpack libdtkwidget-dev_5.5.17.1-1~exp1_amd64.deb ...
> Unpacking libdtkwidget-dev:amd64 (5.5.17.1-1~exp1) over (2.1.1-1build3) ...
> dpkg: dependency problems prevent configuration of libdtkwidget-dev:amd64:
>  libdtkwidget-dev:amd64 depends on libcups2-dev; however:
>   Package libcups2-dev is not installed.
>  libdtkwidget-dev:amd64 depends on libdtkcore-dev (>= 5.5.17); however:
>   Version of libdtkcore-dev:amd64 on system is 2.1.1-1build1.
>  libdtkwidget-dev:amd64 depends on libdtkgui-dev (>= 5.5.17); however:
>   Package libdtkgui-dev is not installed.
>  libdtkwidget-dev:amd64 depends on libdtkwidget5 (= 5.5.17.1-1~exp1); however:
>   Package libdtkwidget5 is not installed.
>  libdtkwidget-dev:amd64 depends on libqt5svg5-dev; however:
>   Package libqt5svg5-dev is not installed.
> 
> dpkg: error processing package libdtkwidget-dev:amd64 (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  libdtkwidget-dev:amd64
> ❯ sudo apt install libcups2-dev libdtkgui-dev libdtkwidget5 libqt5svg5-dev
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package libdtkgui-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> Package libdtkwidget5 is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'libdtkgui-dev' has no installation candidate
> E: Package 'libdtkwidget5' has no installation candidate
> ```

This's really troublesome.
Thank you for your support!
