### ISSUE TITLE
Can not print document with deepin-reader

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/deepin-reader#24]
The deepin-reader printer window is empty.
![2021-09-06 10-14-02 的屏幕截图](https://user-images.githubusercontent.com/1880237/132151053-e3eb9af4-2ddd-4874-b520-652f48683789.png)

**Comment by ifdu-code** [comment]
> The deepin-reader printer window is empty.
> ![2021-09-06 10-14-02 的屏幕截图](https://user-images.githubusercontent.com/1880237/132151053-e3eb9af4-2ddd-4874-b520-652f48683789.png)

So far, we have not encountered such a problem. 
Please provide more detailed information, such as application version, etc.
Thank you for your support!

**Comment by hillwoodroc** [comment]
version 5.9.13
gdb output:
```
2021-09-13, 20:48:50.779 [Warning] [  ] Non-native QFileDialog supports only local files
2021-09-13, 20:48:50.782 [Warning] [  ] Non-native QFileDialog supports only local files
2021-09-13, 20:48:50.783 [Warning] [  ] Non-native QFileDialog supports only local files
2021-09-13, 20:48:50.783 [Warning] [  ] Non-native QFileDialog supports only local files
2021-09-13, 20:48:50.784 [Warning] [  ] Non-native QFileDialog supports only local files
2021-09-13, 20:48:50.787 [Warning] [  ] Non-native QFileDialog supports only local files
```

**Comment by ifdu-code** [comment]
> version 5.9.13
> gdb output:
> 
> ```
> 2021-09-13, 20:48:50.779 [Warning] [  ] Non-native QFileDialog supports only local files
> 2021-09-13, 20:48:50.782 [Warning] [  ] Non-native QFileDialog supports only local files
> 2021-09-13, 20:48:50.783 [Warning] [  ] Non-native QFileDialog supports only local files
> 2021-09-13, 20:48:50.783 [Warning] [  ] Non-native QFileDialog supports only local files
> 2021-09-13, 20:48:50.784 [Warning] [  ] Non-native QFileDialog supports only local files
> 2021-09-13, 20:48:50.787 [Warning] [  ] Non-native QFileDialog supports only local files
> ```

This problem has been fixed at [https://github.com/linuxdeepin/dtkwidget/commit/cedbe540bdcfb5672f97763abb8cf1f79439ec4c](https://github.com/linuxdeepin/dtkwidget/commit/cedbe540bdcfb5672f97763abb8cf1f79439ec4c)

**Comment by hillwoodroc** [comment]
Thanks, confirm it works.
