### ISSUE TITLE
文档查看器，在选择文字高亮后有一定概率在更换颜色时，旧的高亮颜色不消失，新的高亮颜色与旧的高亮颜色重叠。

### ISSUE THREAD

**Issue by deltacatxx** [linuxdeepin/deepin-reader#25]
文档查看器，在选择文字高亮后有一定概率在更换颜色时，旧的高亮颜色不消失，新的高亮颜色与旧的高亮颜色重叠。
如图
![截图_选择区域_20211101003420](https://user-images.githubusercontent.com/71071459/139593727-77b8b383-42cf-4a22-b1d3-5e90ba380bc4.png)

**Comment by Sky-Asher** [comment]
我会将此问题反馈给研发排查，感谢您的支持！

**Comment by ifdu-code** [comment]
> 文档查看器，在选择文字高亮后有一定概率在更换颜色时，旧的高亮颜色不消失，新的高亮颜色与旧的高亮颜色重叠。 如图 ![截图_选择区域_20211101003420](https://user-images.githubusercontent.com/71071459/139593727-77b8b383-42cf-4a22-b1d3-5e90ba380bc4.png)

这里利用了颜料混合的处理逻辑，不同高亮色混合成其他颜色。
比如黄+蓝=绿。
![image](https://user-images.githubusercontent.com/79692260/141710025-3695692b-b29f-4f3c-beb7-b23f785459a0.png)

**Comment by deltacatxx** [comment]
> 这里利用了颜料混合的原理，不同高亮色混合成其他颜色。 比如黄+蓝=绿。 ![image](https://user-images.githubusercontent.com/79692260/141710025-3695692b-b29f-4f3c-beb7-b23f785459a0.png)

了解，不过现在发现，文档查看器的右键取消高亮功能用不了。文字显示灰色，无法点击

![截图_选择区域_20211115122216](https://user-images.githubusercontent.com/71071459/141722129-6ecd17b2-53d5-4586-a5c4-907e8b57241b.png)

**Comment by ifdu-code** [comment]
> > 这里利用了颜料混合的原理，不同高亮色混合成其他颜色。 比如黄+蓝=绿。 ![image](https://user-images.githubusercontent.com/79692260/141710025-3695692b-b29f-4f3c-beb7-b23f785459a0.png)
> 
> 了解，不过现在发现，文档查看器的右键取消高亮功能用不了。文字显示灰色，无法点击
> 
> ![截图_选择区域_20211115122216](https://user-images.githubusercontent.com/71071459/141722129-6ecd17b2-53d5-4586-a5c4-907e8b57241b.png)

没能复现出这个问题。
这个是必现的吗？请提供下你使用的应用版本以及复现手法。

**Comment by deltacatxx** [comment]
> 没能复现出这个问题。 这个是必现的吗？请提供下你使用的应用版本以及复现手法。

版本是 5.9.17
刚发现直接在已经高亮的区域右键就可以取消高亮了。
我之前都是选中高亮区域后再右键选择……这时无法取消。
为了方便解释，上传了个视频

https://user-images.githubusercontent.com/71071459/141728910-336a6408-c884-40f0-9ace-de54e6b50138.mp4

**Comment by ifdu-code** [comment]
> > 没能复现出这个问题。 这个是必现的吗？请提供下你使用的应用版本以及复现手法。
> 
> 版本是 5.9.17 刚发现直接在已经高亮的区域右键就可以取消高亮了。 我之前都是选中高亮区域后再右键选择……这时无法取消。 为了方便解释，上传了个视频
> 
>  default.mp4

那这是正常的，鼠标滑动选中默认是高亮的操作，代码里就是把取消高亮的菜单给置灰处理。

**Comment by deltacatxx** [comment]
> 那这是正常的，鼠标滑动选中默认是高亮的操作，代码里就是把取消高亮的菜单给置灰处理。

好的，非常感谢
