### ISSUE TITLE
Support for viewing 3D content in PDFs

### ISSUE THREAD

**Issue by Atalanttore** [linuxdeepin/deepin-reader#9]
Hi

As a new feature, I would like to suggest support for displaying 3D content in PDFs (usually referred to as 3D PDFs).

Professionally I have a lot to do with 3D PDFs and the lack of 3D PDF viewers for Linux (there simply isn't one) keeps me from migrating to (Deepin) Linux.

**Comment by samson-sofun** [comment]
The purpose of deepin-reader is to support more document formats and common formats are preferred. 3D PDF will be developed later as a new format. But it's not the highest priority now.Thank you for your attention

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
